version: '3'
services:
  web:
    build: .
    ports:
      - '127.0.0.1:3003:80'
    env_file: ./.env
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    ports:
      - '127.0.0.1:3004:5432'
    env_file:
      - ./.postgres.env
    restart: unless-stopped
    volumes:
      - /data/kupi-svoe-api/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
