export enum OrderStatus {
  CREATED = 'CREATED',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  AVAILABILITY_CHECK = 'AVAILABILITY_CHECK',
  FINDING_AN_ALTERNATIVE = 'FINDING_AN_ALTERNATIVE',
  IN_THE_PROCESS_OF_DELIVERY = 'IN_THE_PROCESS_OF_DELIVERY',
  DELIVERED = 'DELIVERED',
  IN_PROCESSING = 'IN_PROCESSING',
}
